[programs.localnet]
faktor = "J5oRyhTB7gzKihVABnjmBFJj85v5nBUkh2Ey7bBdiAfu"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
