[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
faktor = "GxReFFF7LTe64UeY9ijUmmqUiDdYKTVD8pw6FLZxEQ8i"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
