[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
faktor = "8BHW97BHkSKUHjTxHd6g7eGRfLxQfmXniEMcAskxQTKi"

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "mocha -t 1000000 tests/"
