[programs.localnet]
faktor = "ctoeKp85DThYGxzqcrjPd6w2EG1t43uKJJuxiZFzYWv"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 --paths tests/*.spec.ts"
